### ISSUE TITLE
Konstantin's tasks

### ISSUE THREAD

**Issue by Oleg-Storozhev** [Java-Camp/Back-end#37]
- [x] Call creation with YI (input of fields: name, account type, currency, description) (#31)
- [x] Rest on getting account data (#32)
- [x] Rest request to create a record (#32)
